Реализован фукнционал в соответствии с ТЗ
adrzdv/java-filmorate pull request #4
Opened 2024-08-09 15:16 UTC by adrzdv

2024-08-09 18:24 UTC, kriwsha requested changes

2024-08-09 18:24 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Не следует смешивать сторадж и контроллер. Между ними следует держать сервис. Представьте, вам потребуется изменить хранилище, где будет другой способ взаимодействия с базой данных. Тогда вам придется вносить изменения в контроллеры. А если вам придется поддерживать две версии, то это будет очень сложной задачей. В случае, если между контроллером и хранилищем будет еще класс сервис, который будет проксировать запросы, вам при смене хранилище достаточно будет подменить один сервис другим за счет слабой связности приложения. И поддерживать две версии всего приложения не придется - все будет зависеть от конфигураций, которыми вы будете управлять

2024-08-09 18:24 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage userStorage;
Здесь тот же совет

2024-08-09 18:24 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Collection<Film> getMostPopular(int count) {
Эту логику я бы советовал делать на стороне базы данных. Если у вас в базе будет информация о всех снятых фильмах, ваше приложение просто не выдержит. В вашем случае под базой данных я понимаю сторадж, который в будущем будет заменен на реальную базу данных

2024-08-09 18:24 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Collection<User> commonUsers = userStorage.getAll().stream()
Здесь тоже выборка всех пользователей... А если их будет хотя бы 10млн?

2024-08-11 06:50 UTC, kriwsha requested changes

2024-08-11 06:50 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.getFilmStorage().addNew(film);
Нет, так тоже не надо делать! Вы не должны вызывать из контроллера методы стораджа. Представьте, что названия самих методов изменятся, тогда это исправление не поможет решить проблему. Я предлагаю сделать сквозные методы. Примерно так:

```
class MyController {
  private MyService myService;
  public Object addNew(Object obj) {
      myService.addNew(obj);
   }
}

class MyService {
   private MyStorage myStorage;
   public Object addNew(Object obj) {
      myStorage.addNew(obj);
   }
}

class MyStorage {
   public Object addNew(Object obj) {
      /// ....
   }
}
```

В этом случае контроллер абсолютно ничего не знает о сторадже - между ними находится сервисный слой, который в должен управлять основной логикой.

2024-08-11 06:50 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return userService.getUserStorage().addNew(user);
Здесь также следует поправить

2024-08-11 12:09 UTC, adrzdv commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.getFilmStorage().addNew(film);
Да, согласен, посыл изначально был верный, это я решил какой-то импровизацией заняться

2024-08-11 18:20 UTC, kriwsha approved these changes

2024-08-11 18:45 UTC, merged